//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EscuelaCdis__DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumno
    {
        public Alumno()
        {
            this.MateriaAlumno = new HashSet<MateriaAlumno>();
        }
    
        public int matricula { get; set; }
        public string nombre { get; set; }
        public System.DateTime FechaDeNacimiento { get; set; }
        public int semestre { get; set; }
        public int facultad { get; set; }
        public int municipio { get; set; }
    
        public virtual Facultades Facultad1 { get; set; }
        public virtual Municipio Municipio1 { get; set; }
        public virtual ICollection<MateriaAlumno> MateriaAlumno { get; set; }
    }
}
